import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}


//apis
//https://www.freetogame.com/api/games
//https://www.freetogame.com/api/games?platform=pc --- platform pc\browser
//https://www.freetogame.com/api/games?category=shooter --- category : MMO\MMORPG\shooter\strategy\moba\card\racing\sports\social\fighting
//https://www.freetogame.com/api/games?sort-by=alphabetical --- sort-by relevance\popularity\relasedata\alphabetical
//https://www.freetogame.com/api/games?platform=browser&category=mmorpg&sort-by=release-date --- Games by platform & category & sorted
//https://www.freetogame.com/api/filter?tag=3d.mmorpg.fantasy.pvp&platform=pc --- Filter Games by multiple tags for personalized results
//https://www.freetogame.com/api/game?id=452 -- details
//https://www.freetogame.com/api/Coming Soon 
//
//